name: Trigger Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy
jobs:
  build:
    name: run
    environment: "daily_rebuild"
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: id -a;pwd;ls -al
